// =============================================================================
//    Copyright (c) 2025 - 2026 Haixing Hu.
//
//    SPDX-License-Identifier: Apache-2.0
//
//    Licensed under the Apache License, Version 2.0.
// =============================================================================
//! Tests for field-level attributes generated by the `Redact` derive.

use std::collections::HashMap;

use qubit_redact::Redact;
use qubit_redact_derive::Redact;

/// Nested record whose ordinary `Debug` output deliberately remains visible.
#[derive(Debug, Redact)]
struct Inner {
    /// Secret used to prove that plain fields do not recurse implicitly.
    #[redact(level = "secret")]
    secret: String,
}

/// Marker that intentionally implements no formatting trait.
struct NotDebug;

/// Record combining explicit masking, plain formatting, and omission.
#[derive(Redact)]
struct Outer {
    /// Optional medium-sensitivity value.
    #[redact(level = "medium")]
    mobile: Option<String>,
    /// Plain nested value that must use ordinary `Debug`.
    inner: Inner,
    /// Internal value omitted without imposing a `Debug` bound.
    #[redact(skip)]
    cache: NotDebug,
}

/// Record covering every accepted case-sensitive sensitivity spelling.
#[derive(Redact)]
struct AllLevels {
    /// Low-sensitivity value.
    #[redact(level = "low")]
    low: String,
    /// Medium-sensitivity value.
    #[redact(level = "medium")]
    medium: String,
    /// High-sensitivity value.
    #[redact(level = "high")]
    high: String,
    /// Secret value.
    #[redact(level = "secret")]
    secret: String,
}

/// Record whose original formatting traits are generated from `Redact`.
#[derive(Redact)]
#[redact(debug, display)]
struct SafeFormatting {
    /// Visible value rendered with ordinary `Debug`.
    visible: &'static str,
    /// Secret value rendered with the strongest mask.
    #[redact(level = "secret")]
    secret: String,
    /// Omitted value that intentionally implements no formatting trait.
    #[redact(skip)]
    ignored: NotDebug,
}

/// Tuple record covering positional masking and omission.
#[derive(Redact)]
struct TupleRecord(
    /// Secret positional field.
    #[redact(level = "secret")]
    String,
    /// Omitted positional field without a formatting bound.
    #[redact(skip)]
    NotDebug,
);

/// Unit record with no fields to inspect.
#[derive(Redact)]
struct UnitRecord;

/// Enum covering named, tuple, unit, nested, and map redaction paths.
#[derive(Redact)]
enum AuditEvent {
    /// Named fields preserve their field labels.
    Named {
        /// Visible field using ordinary formatting.
        visible: &'static str,
        /// Secret field replaced by the configured mask.
        #[redact(level = "secret")]
        secret: String,
        /// Omitted field without a formatting bound.
        #[redact(skip)]
        ignored: NotDebug,
    },
    /// Tuple fields preserve their positional debug shape.
    Tuple(
        /// Secret positional field.
        #[redact(level = "secret")]
        String,
        /// Visible positional field.
        &'static str,
        /// Omitted positional field.
        #[redact(skip)]
        NotDebug,
    ),
    /// Nested objects and maps use their explicit redaction capabilities.
    Composite {
        /// Nested domain object.
        #[redact(nested)]
        inner: Inner,
        /// Values classified using their map keys.
        #[redact(map)]
        metadata: HashMap<String, String>,
    },
    /// Unit variant with no data to redact.
    Unit,
}

/// Verifies explicit masking, complete omission, and non-recursive plain
/// fields.
#[test]
fn test_level_masks_skip_omits_and_plain_field_does_not_recurse() {
    let value = Outer {
        mobile: Some("13800138000".to_owned()),
        inner: Inner {
            secret: "raw-inner".to_owned(),
        },
        cache: NotDebug,
    };
    let _ = &value.cache;

    let rendered = format!("{:?}", value.redacted());

    assert!(!rendered.contains("13800138000"));
    assert!(rendered.contains("raw-inner"));
    assert!(!rendered.contains("cache"));
}

/// Verifies that all four accepted level spellings select their configured
/// masks.
#[test]
fn test_level_accepts_all_supported_case_sensitive_values() {
    let value = AllLevels {
        low: "low-value".to_owned(),
        medium: "medium-value".to_owned(),
        high: "high-value".to_owned(),
        secret: "secret-value".to_owned(),
    };

    let rendered = format!("{:?}", value.redacted());

    assert!(!rendered.contains("low-value"));
    assert!(!rendered.contains("medium-value"));
    assert!(!rendered.contains("high-value"));
    assert!(!rendered.contains("secret-value"));
    assert!(rendered.contains("<redacted>"));
}

/// Verifies generated formatting delegates to the existing redacted view.
#[test]
fn test_safe_formatting_matches_explicit_redacted_view() {
    let value = SafeFormatting {
        visible: "shown",
        secret: "formatting-secret".to_owned(),
        ignored: NotDebug,
    };
    let _ = &value.ignored;

    assert_eq!(format!("{value:?}"), format!("{:?}", value.redacted()));
    assert_eq!(format!("{value:#?}"), format!("{:#?}", value.redacted()));
    assert_eq!(format!("{value}"), format!("{}", value.redacted()));
    assert!(!format!("{value:?}").contains("formatting-secret"));
}

/// Verifies tuple and unit structs preserve their standard debug shapes.
#[test]
fn test_tuple_and_unit_structs_preserve_debug_shapes() {
    let tuple = TupleRecord(String::from("raw-tuple"), NotDebug);
    let _ = &tuple.1;

    assert_eq!(
        format!("{:?}", tuple.redacted()),
        r#"TupleRecord("<redacted>")"#,
    );
    assert_eq!(format!("{:?}", UnitRecord.redacted()), "UnitRecord");
}

/// Verifies every enum variant shape preserves its standard debug form while
/// applying field-level redaction controls.
#[test]
fn test_enum_variants_preserve_shapes_and_redact_selected_fields() {
    let named = AuditEvent::Named {
        visible: "shown",
        secret: String::from("raw-named"),
        ignored: NotDebug,
    };
    let tuple = AuditEvent::Tuple(String::from("raw-tuple"), "shown", NotDebug);
    let composite = AuditEvent::Composite {
        inner: Inner {
            secret: String::from("raw-nested"),
        },
        metadata: HashMap::from([(String::from("token"), String::from("raw-map"))]),
    };
    let AuditEvent::Named { ignored, .. } = &named else {
        unreachable!("the constructed variant is named");
    };
    let _ = ignored;

    let named_rendered = format!("{:?}", named.redacted());
    let tuple_rendered = format!("{:?}", tuple.redacted());
    let composite_rendered = format!("{:?}", composite.redacted());

    assert_eq!(
        named_rendered,
        r#"Named { visible: "shown", secret: "<redacted>" }"#,
    );
    assert_eq!(tuple_rendered, r#"Tuple("<redacted>", "shown")"#);
    assert!(!composite_rendered.contains("raw-nested"));
    assert!(!composite_rendered.contains("raw-map"));
    assert_eq!(format!("{:?}", AuditEvent::Unit.redacted()), "Unit");
}
