// =============================================================================
//    Copyright (c) 2025 - 2026 Haixing Hu.
//
//    SPDX-License-Identifier: Apache-2.0
//
//    Licensed under the Apache License, Version 2.0.
// =============================================================================
//! Tests for field-level attributes generated by the `Redact` derive.

use qubit_redact::Redact;

/// Nested record whose ordinary `Debug` output deliberately remains visible.
#[derive(Debug, Redact)]
struct Inner {
    /// Secret used to prove that plain fields do not recurse implicitly.
    #[redact(level = "secret")]
    secret: String,
}

/// Marker that intentionally implements no formatting trait.
struct NotDebug;

/// Record combining explicit masking, plain formatting, and omission.
#[derive(Redact)]
struct Outer {
    /// Optional medium-sensitivity value.
    #[redact(level = "medium")]
    mobile: Option<String>,
    /// Plain nested value that must use ordinary `Debug`.
    inner: Inner,
    /// Internal value omitted without imposing a `Debug` bound.
    #[redact(skip)]
    cache: NotDebug,
}

/// Record covering every accepted case-sensitive sensitivity spelling.
#[derive(Redact)]
struct AllLevels {
    /// Low-sensitivity value.
    #[redact(level = "low")]
    low: String,
    /// Medium-sensitivity value.
    #[redact(level = "medium")]
    medium: String,
    /// High-sensitivity value.
    #[redact(level = "high")]
    high: String,
    /// Secret value.
    #[redact(level = "secret")]
    secret: String,
}

/// Verifies explicit masking, complete omission, and non-recursive plain
/// fields.
#[test]
fn test_level_masks_skip_omits_and_plain_field_does_not_recurse() {
    let value = Outer {
        mobile: Some("13800138000".to_owned()),
        inner: Inner {
            secret: "raw-inner".to_owned(),
        },
        cache: NotDebug,
    };
    let _ = &value.cache;

    let rendered = format!("{:?}", value.redacted());

    assert!(!rendered.contains("13800138000"));
    assert!(rendered.contains("raw-inner"));
    assert!(!rendered.contains("cache"));
}

/// Verifies that all four accepted level spellings select their configured
/// masks.
#[test]
fn test_level_accepts_all_supported_case_sensitive_values() {
    let value = AllLevels {
        low: "low-value".to_owned(),
        medium: "medium-value".to_owned(),
        high: "high-value".to_owned(),
        secret: "secret-value".to_owned(),
    };

    let rendered = format!("{:?}", value.redacted());

    assert!(!rendered.contains("low-value"));
    assert!(!rendered.contains("medium-value"));
    assert!(!rendered.contains("high-value"));
    assert!(!rendered.contains("secret-value"));
    assert!(rendered.contains("<redacted>"));
}
