// =============================================================================
//    Copyright (c) 2026 Haixing Hu.
//    SPDX-License-Identifier: Apache-2.0
// =============================================================================
//! Scalar leaf capability for primitive values and transparent newtypes.

use super::RedactLevelValue;

/// A single scalar representation usable with an explicit redaction level.
///
/// Derive this trait for a one-field struct whose field is also a scalar.
/// Containers are level-capable but are not scalars. This capability does not
/// choose a sensitivity or implement Debug, Display, or ordinary Serialize.
/// Implementations should be generated by `#[derive(RedactScalar)]`.
pub trait RedactScalar: RedactLevelValue {}

macro_rules! scalar {
    ($($ty:ty),+ $(,)?) => { $(impl RedactScalar for $ty {})+ };
}

scalar!(
    String,
    str,
    char,
    bool,
    i8,
    i16,
    i32,
    i64,
    i128,
    isize,
    u8,
    u16,
    u32,
    u64,
    u128,
    usize,
    f32,
    f64,
    std::borrow::Cow<'_, str>
);
impl<T: RedactScalar + ?Sized> RedactScalar for &T {}
#[cfg(feature = "serde")]
impl RedactScalar for bigdecimal::BigDecimal {}
