// =============================================================================
//    Copyright (c) 2026 Haixing Hu.
//
//    SPDX-License-Identifier: Apache-2.0
// =============================================================================
//! User field names must not shadow bindings generated by the derive macro.

#![cfg(feature = "derive")]

use qubit_redact::Redact;
use qubit_redact::Redactor;

/// Builds enums with adversarial field names and distinct observable values.
macro_rules! collision_enum {
    ($name:ident $(, $attribute:meta)*) => {
        #[derive(Redact)]
        $(#[$attribute])*
        enum $name {
            Named {
                writer: String,
                __fields: String,
                policy: String,
                serializer: String,
                state: String,
                field_count: String,
                __qubit_redact_serialized_0: String,
                __qubit_redact_field_0: String,
                r#type: String,
                #[redact(keyed_by = policy)]
                value: String,
                #[redact(keyed_by = r#type)]
                public_value: String,
            },
        }

        impl $name {
            /// Returns a secret keyed by `policy` and a public raw-identifier key.
            fn fixture() -> Self {
                Self::Named {
                    writer: "writer-value".to_owned(),
                    __fields: "fields-value".to_owned(),
                    policy: "password".to_owned(),
                    serializer: "serializer-value".to_owned(),
                    state: "state-value".to_owned(),
                    field_count: "count-value".to_owned(),
                    __qubit_redact_serialized_0: "carrier-value".to_owned(),
                    __qubit_redact_field_0: "binding-value".to_owned(),
                    r#type: "region".to_owned(),
                    value: "raw-secret".to_owned(),
                    public_value: "eu-west".to_owned(),
                }
            }
        }
    };
}

collision_enum!(Text);

/// Checks aliasing in the borrowing writer independently of the Serde feature.
#[test]
fn test_named_enum_writer_uses_isolated_bindings() {
    let value = Text::fixture();
    let redactor = Redactor::standard();
    let output = redactor.redact(&value);
    let text = output.text().as_str();
    for visible in [
        "writer-value",
        "fields-value",
        "serializer-value",
        "state-value",
        "count-value",
        "carrier-value",
        "binding-value",
        "eu-west",
    ] {
        assert!(text.contains(visible), "missing {visible}: {text}");
    }
    assert!(!text.contains("raw-secret"), "{text}");
}

#[cfg(feature = "serde")]
mod serde {
    use qubit_redact::Redact;
    #[cfg(feature = "serde")]
    use qubit_redact::RedactionPolicy;
    use qubit_redact::Redactor;
    #[cfg(feature = "serde")]
    use qubit_redact::domain::internal::RedactedSerializeRef;

    collision_enum!(External, redact(serde));
    collision_enum!(Internal, redact(serde), serde(tag = "kind"));
    collision_enum!(Adjacent, redact(serde), serde(tag = "kind", content = "payload"));
    collision_enum!(Untagged, redact(serde), serde(untagged));

    #[derive(Redact)]
    #[redact(serde)]
    enum SkippedKey {
        Named {
            #[serde(skip)]
            policy: String,
            #[redact(keyed_by = policy)]
            value: String,
        },
    }

    /// A key omitted from the wire representation still classifies its sibling.
    #[test]
    fn test_keyed_enum_can_reference_a_serde_skipped_key() {
        let policy = RedactionPolicy::standard();
        let value = SkippedKey::Named {
            policy: "password".to_owned(),
            value: "secret".to_owned(),
        };
        let encoded =
            serde_json::to_value(RedactedSerializeRef::new(&value, &policy)).expect("skipped key serialization");
        assert_eq!(encoded, serde_json::json!({"Named": {"value": "<redacted>"}}));
    }

    /// Checks all wire representations retain the right values after aliasing.
    #[test]
    fn test_named_enum_serde_representations_use_isolated_bindings() {
        let previous = Redactor::replace_application_default(Redactor::standard());
        let fixtures = [
            (serde_json::to_value(External::fixture()), "/Named"),
            (serde_json::to_value(Internal::fixture()), ""),
            (serde_json::to_value(Adjacent::fixture()), "/payload"),
            (serde_json::to_value(Untagged::fixture()), ""),
        ];
        let _ = Redactor::replace_application_default(previous);
        for (result, pointer) in fixtures {
            let json = result.expect("enum serialization succeeds");
            let fields = json.pointer(pointer).expect("representation payload");
            assert_eq!(fields["writer"], "writer-value");
            assert_eq!(fields["__fields"], "fields-value");
            assert_eq!(fields["policy"], "password");
            assert_eq!(fields["serializer"], "serializer-value");
            assert_eq!(fields["state"], "state-value");
            assert_eq!(fields["field_count"], "count-value");
            assert_eq!(fields["__qubit_redact_serialized_0"], "carrier-value");
            assert_eq!(fields["__qubit_redact_field_0"], "binding-value");
            assert_eq!(fields["type"], "region");
            assert_eq!(fields["public_value"], "eu-west");
            assert_ne!(fields["value"], "raw-secret");
        }
    }
}
