// =============================================================================
//    Copyright (c) 2026 Haixing Hu.
//
//    SPDX-License-Identifier: Apache-2.0
//
//    Licensed under the Apache License, Version 2.0 (the "License");
//    you may not use this file except in compliance with the License.
//    You may obtain a copy of the License at
//
//        https://www.apache.org/licenses/LICENSE-2.0
//
//    Unless required by applicable law or agreed to in writing, software
//    distributed under the License is distributed on an "AS IS" BASIS,
//    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//    See the License for the specific language governing permissions and
//    limitations under the License.
// =============================================================================
//! Compile tests for runtime trait-bound diagnostics generated by the derive
//! crate.

/// Verifies nested derive errors point at stable runtime trait implementations.
#[test]
fn test_runtime_trait_bound_diagnostics() {
    let tests = trybuild::TestCases::new();
    tests.compile_fail(
        "tests/fixtures/domain_derive/fail/redact_mut_borrowed_field.rs",
    );
    tests.compile_fail(
        "tests/fixtures/domain_derive/fail/redact_mut_nested_without_redact_mut.rs",
    );
}
