// =============================================================================
//    Copyright (c) 2026 Haixing Hu.
//
//    SPDX-License-Identifier: Apache-2.0
//
//    Licensed under the Apache License, Version 2.0.
// =============================================================================
//! Compile tests for runtime trait-bound diagnostics generated by the derive
//! crate.

/// Verifies nested derive errors point at stable runtime trait implementations.
#[test]
fn test_runtime_trait_bound_diagnostics() {
    let tests = trybuild::TestCases::new();
    tests.compile_fail(
        "tests/fixtures/domain_derive/fail/redact_mut_borrowed_field.rs",
    );
    tests.compile_fail(
        "tests/fixtures/domain_derive/fail/redact_mut_nested_without_redact_mut.rs",
    );
}
