// qubit-style: allow multiple-public-types
// qubit-style: allow all

use std::borrow::Cow;
use std::cell::RefCell;
use std::collections::BTreeMap;
use std::collections::HashMap;

mod serde {
    pub use ::serde::Serialize;
    pub use ::serde::Serializer;

    pub mod ser {
        pub use ::serde::ser::SerializeMap;
        pub use ::serde::ser::SerializeSeq;
        pub use ::serde::ser::SerializeTuple;
    }
}

use self::serde::ser::SerializeMap;
use self::serde::ser::SerializeSeq;
use self::serde::ser::SerializeTuple;

#[allow(dead_code)]
#[derive(Clone, Copy)]
struct StructuredSerdeBudget {
    policy: crate::policy::RedactionLimits,
    depth: usize,
    nodes: usize,
    collection_items: usize,
    input_bytes: usize,
}

thread_local! {
    static STRUCTURED_SERDE_BUDGET: RefCell<Option<StructuredSerdeBudget>> = const { RefCell::new(None) };
}

/// Hidden scope that shares structural Serde admission across nested derives.
#[doc(hidden)]
pub struct RedactSerializeScope {
    previous: Option<StructuredSerdeBudget>,
}

impl RedactSerializeScope {
    /// Starts one policy-scoped structured serialization budget.
    #[must_use]
    pub fn new(policy: &crate::RedactionPolicy) -> Self {
        let previous = STRUCTURED_SERDE_BUDGET.with(|slot| {
            slot.replace(Some(StructuredSerdeBudget {
                policy: *policy.limits(),
                depth: 0,
                nodes: 0,
                collection_items: 0,
                input_bytes: 0,
            }))
        });
        Self { previous }
    }
}

impl Drop for RedactSerializeScope {
    fn drop(&mut self) {
        let previous = self.previous.take();
        STRUCTURED_SERDE_BUDGET.with(|slot| {
            slot.replace(previous);
        });
    }
}

#[allow(dead_code)]
fn admit_node() -> bool {
    STRUCTURED_SERDE_BUDGET.with(|slot| {
        let mut state = slot.borrow_mut();
        let Some(state) = state.as_mut() else {
            return true;
        };
        if state.policy.max_depth().is_some_and(|maximum| state.depth >= maximum)
            || state.policy.max_nodes().is_some_and(|maximum| state.nodes >= maximum)
        {
            return false;
        }
        state.depth += 1;
        state.nodes += 1;
        true
    })
}

#[allow(dead_code)]
fn leave_node() {
    STRUCTURED_SERDE_BUDGET.with(|slot| {
        if let Some(state) = slot.borrow_mut().as_mut() {
            state.depth = state.depth.saturating_sub(1);
        }
    });
}

fn admit_collection_items(count: usize) -> bool {
    STRUCTURED_SERDE_BUDGET.with(|slot| {
        let mut state = slot.borrow_mut();
        let Some(state) = state.as_mut() else {
            return true;
        };
        let next = state.collection_items.saturating_add(count);
        if state
            .policy
            .max_collection_items()
            .is_some_and(|maximum| next > maximum)
        {
            return false;
        }
        state.collection_items = next;
        true
    })
}

#[allow(dead_code)]
fn admit_input(bytes: usize) -> bool {
    STRUCTURED_SERDE_BUDGET.with(|slot| {
        let mut state = slot.borrow_mut();
        let Some(state) = state.as_mut() else {
            return true;
        };
        let next = state.input_bytes.saturating_add(bytes);
        if next > state.policy.max_input_bytes() {
            return false;
        }
        state.input_bytes = next;
        true
    })
}

/// Runs one generated structured serializer under the shared budget.
#[doc(hidden)]
pub fn serialize_structured<S, F>(serializer: S, policy: &crate::RedactionPolicy, body: F) -> Result<S::Ok, S::Error>
where
    S: serde::Serializer,
    F: FnOnce(S) -> Result<S::Ok, S::Error>,
{
    if !admit_node() {
        return serializer.serialize_str(policy.masking().mask_opaque(crate::Sensitivity::Secret).as_ref());
    }
    let result = body(serializer);
    leave_node();
    result
}

/// Internal structured serialization capability generated by the derive crate.
#[doc(hidden)]
pub trait RedactSerialize {
    fn serialize_redacted<S>(&self, serializer: S, policy: &crate::RedactionPolicy) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer;
}

/// Internal structured serialization capability for scalar level fields.
#[doc(hidden)]
pub trait RedactLevelSerialize {
    fn serialize_redacted_level<S>(
        &self,
        serializer: S,
        policy: &crate::RedactionPolicy,
        level: crate::Sensitivity,
    ) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer;
}

/// Borrowed serializer adapter for one level field.
#[doc(hidden)]
pub struct RedactedLevelSerializeRef<'value, 'policy, T: ?Sized> {
    value: &'value T,
    policy: &'policy crate::RedactionPolicy,
    level: crate::Sensitivity,
}

impl<'value, 'policy, T: ?Sized> RedactedLevelSerializeRef<'value, 'policy, T> {
    /// Creates a policy-carrying borrowed level adapter.
    #[must_use]
    pub fn new(value: &'value T, policy: &'policy crate::RedactionPolicy, level: crate::Sensitivity) -> Self {
        Self { value, policy, level }
    }
}

impl<T: ?Sized + RedactLevelSerialize> serde::Serialize for RedactedLevelSerializeRef<'_, '_, T> {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        self.value.serialize_redacted_level(serializer, self.policy, self.level)
    }
}

macro_rules! scalar_level_serialize {
    ($($type:ty),+ $(,)?) => {
        $(impl RedactLevelSerialize for $type {
            fn serialize_redacted_level<S>(
                &self,
                serializer: S,
                policy: &crate::RedactionPolicy,
                level: crate::Sensitivity,
            ) -> Result<S::Ok, S::Error>
            where
                S: serde::Serializer,
            {
                if policy.is_disabled() {
                    serde::Serialize::serialize(self, serializer)
                } else {
                    let masked = policy.masking().mask_opaque(level);
                    serializer.serialize_str(masked.as_ref())
                }
            }
        })+
    };
}

scalar_level_serialize!(
    String, str, char, bool, i8, i16, i32, i64, i128, isize, u8, u16, u32, u64, u128, usize, f32, f64
);

#[cfg(feature = "serde")]
impl RedactLevelSerialize for bigdecimal::BigDecimal {
    fn serialize_redacted_level<S>(
        &self,
        serializer: S,
        policy: &crate::RedactionPolicy,
        level: crate::Sensitivity,
    ) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        if policy.is_disabled() {
            serde::Serialize::serialize(self, serializer)
        } else {
            let masked = policy.masking().mask_opaque(level);
            serializer.serialize_str(masked.as_ref())
        }
    }
}

impl<'a> RedactLevelSerialize for Cow<'a, str> {
    fn serialize_redacted_level<S>(
        &self,
        serializer: S,
        policy: &crate::RedactionPolicy,
        level: crate::Sensitivity,
    ) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        if policy.is_disabled() {
            serde::Serialize::serialize(self, serializer)
        } else {
            let masked = policy.masking().mask_opaque(level);
            serializer.serialize_str(masked.as_ref())
        }
    }
}

impl RedactLevelSerialize for &str {
    fn serialize_redacted_level<S>(
        &self,
        serializer: S,
        policy: &crate::RedactionPolicy,
        level: crate::Sensitivity,
    ) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        if policy.is_disabled() {
            serde::Serialize::serialize(self, serializer)
        } else {
            let masked = policy.masking().mask_opaque(level);
            serializer.serialize_str(masked.as_ref())
        }
    }
}

impl<T: RedactLevelSerialize> RedactLevelSerialize for Option<T> {
    fn serialize_redacted_level<S>(
        &self,
        serializer: S,
        policy: &crate::RedactionPolicy,
        level: crate::Sensitivity,
    ) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        match self {
            Some(value) => value.serialize_redacted_level(serializer, policy, level),
            None => serializer.serialize_none(),
        }
    }
}

impl<T: RedactLevelSerialize> RedactLevelSerialize for Vec<T> {
    fn serialize_redacted_level<S>(
        &self,
        serializer: S,
        policy: &crate::RedactionPolicy,
        level: crate::Sensitivity,
    ) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        if !admit_collection_items(self.len()) {
            return serializer.serialize_str(policy.masking().mask_opaque(crate::Sensitivity::Secret).as_ref());
        }
        let mut sequence = serializer.serialize_seq(Some(self.len()))?;
        for value in self {
            sequence.serialize_element(&RedactedLevelSerializeRef::new(value, policy, level))?;
        }
        sequence.end()
    }
}

impl<T: RedactLevelSerialize, const N: usize> RedactLevelSerialize for [T; N] {
    fn serialize_redacted_level<S>(
        &self,
        serializer: S,
        policy: &crate::RedactionPolicy,
        level: crate::Sensitivity,
    ) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        if !admit_collection_items(N) {
            return serializer.serialize_str(policy.masking().mask_opaque(crate::Sensitivity::Secret).as_ref());
        }
        let mut sequence = serializer.serialize_seq(Some(N))?;
        for value in self {
            sequence.serialize_element(&RedactedLevelSerializeRef::new(value, policy, level))?;
        }
        sequence.end()
    }
}

macro_rules! tuple_level_serialize {
    ($count:expr; $($name:ident => $index:tt),+) => {
        impl<$($name: RedactLevelSerialize),+> RedactLevelSerialize for ($($name,)+) {
            fn serialize_redacted_level<S>(&self, serializer: S, policy: &crate::RedactionPolicy, level: crate::Sensitivity) -> Result<S::Ok, S::Error>
            where
                S: serde::Serializer,
            {
                if !admit_collection_items($count) {
                    return serializer.serialize_str(
                        policy
                            .masking()
                            .mask_opaque(crate::Sensitivity::Secret)
                            .as_ref(),
                    );
                }
                let mut tuple = serializer.serialize_tuple($count)?;
                $(tuple.serialize_element(&RedactedLevelSerializeRef::new(&self.$index, policy, level))?;)+
                tuple.end()
            }
        }
    };
}

tuple_level_serialize!(1; A => 0);
tuple_level_serialize!(2; A => 0, B => 1);
tuple_level_serialize!(3; A => 0, B => 1, C => 2);
tuple_level_serialize!(4; A => 0, B => 1, C => 2, D => 3);
tuple_level_serialize!(5; A => 0, B => 1, C => 2, D => 3, E => 4);
tuple_level_serialize!(6; A => 0, B => 1, C => 2, D => 3, E => 4, F => 5);
tuple_level_serialize!(7; A => 0, B => 1, C => 2, D => 3, E => 4, F => 5, G => 6);
tuple_level_serialize!(8; A => 0, B => 1, C => 2, D => 3, E => 4, F => 5, G => 6, H => 7);
tuple_level_serialize!(9; A => 0, B => 1, C => 2, D => 3, E => 4, F => 5, G => 6, H => 7, I => 8);
tuple_level_serialize!(10; A => 0, B => 1, C => 2, D => 3, E => 4, F => 5, G => 6, H => 7, I => 8, J => 9);
tuple_level_serialize!(11; A => 0, B => 1, C => 2, D => 3, E => 4, F => 5, G => 6, H => 7, I => 8, J => 9, K => 10);
tuple_level_serialize!(12; A => 0, B => 1, C => 2, D => 3, E => 4, F => 5, G => 6, H => 7, I => 8, J => 9, K => 10, L => 11);

/// Borrowed serializer adapter that carries one immutable redaction policy.
#[doc(hidden)]
pub struct RedactedSerializeRef<'value, 'policy, T: ?Sized> {
    value: &'value T,
    policy: &'policy crate::RedactionPolicy,
}

impl<'value, 'policy, T: ?Sized> RedactedSerializeRef<'value, 'policy, T> {
    /// Creates a policy-carrying borrowed serializer adapter.
    #[must_use]
    pub fn new(value: &'value T, policy: &'policy crate::RedactionPolicy) -> Self {
        Self { value, policy }
    }
}

impl<T: ?Sized + RedactSerialize> serde::Serialize for RedactedSerializeRef<'_, '_, T> {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        self.value.serialize_redacted(serializer, self.policy)
    }
}

impl<T: RedactSerialize> RedactSerialize for Option<T> {
    fn serialize_redacted<S>(&self, serializer: S, policy: &crate::RedactionPolicy) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        match self {
            Some(value) => value.serialize_redacted(serializer, policy),
            None => serializer.serialize_none(),
        }
    }
}

impl<T: RedactSerialize> RedactSerialize for Vec<T> {
    fn serialize_redacted<S>(&self, serializer: S, policy: &crate::RedactionPolicy) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        if !admit_collection_items(self.len()) {
            return serializer.serialize_str(policy.masking().mask_opaque(crate::Sensitivity::Secret).as_ref());
        }
        let mut sequence = serializer.serialize_seq(Some(self.len()))?;
        for value in self {
            sequence.serialize_element(&RedactedSerializeRef::new(value, policy))?;
        }
        sequence.end()
    }
}

impl<T: RedactSerialize, const N: usize> RedactSerialize for [T; N] {
    fn serialize_redacted<S>(&self, serializer: S, policy: &crate::RedactionPolicy) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        if !admit_collection_items(N) {
            return serializer.serialize_str(policy.masking().mask_opaque(crate::Sensitivity::Secret).as_ref());
        }
        let mut sequence = serializer.serialize_seq(Some(N))?;
        for value in self {
            sequence.serialize_element(&RedactedSerializeRef::new(value, policy))?;
        }
        sequence.end()
    }
}

/// Internal structured serialization capability for policy-classified maps.
#[doc(hidden)]
pub trait RedactMapSerialize {
    fn serialize_redacted_map<S>(&self, serializer: S, policy: &crate::RedactionPolicy) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer;
}

/// Borrowed serializer adapter for one policy-classified map.
#[doc(hidden)]
pub struct RedactedMapSerializeRef<'value, 'policy, T: ?Sized> {
    value: &'value T,
    policy: &'policy crate::RedactionPolicy,
}

impl<'value, 'policy, T: ?Sized> RedactedMapSerializeRef<'value, 'policy, T> {
    /// Creates a policy-carrying borrowed map adapter.
    #[must_use]
    pub fn new(value: &'value T, policy: &'policy crate::RedactionPolicy) -> Self {
        Self { value, policy }
    }
}

impl<T: ?Sized + RedactMapSerialize> serde::Serialize for RedactedMapSerializeRef<'_, '_, T> {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        self.value.serialize_redacted_map(serializer, self.policy)
    }
}

macro_rules! map_redact_serialize {
    ($map:ty) => {
        impl<K, V> RedactMapSerialize for $map
        where
            K: AsRef<str> + serde::Serialize,
            V: serde::Serialize,
        {
            fn serialize_redacted_map<S>(
                &self,
                serializer: S,
                policy: &crate::RedactionPolicy,
            ) -> Result<S::Ok, S::Error>
            where
                S: serde::Serializer,
            {
                if !admit_collection_items(self.len()) {
                    return serializer.serialize_str(policy.masking().mask_opaque(crate::Sensitivity::Secret).as_ref());
                }
                let mut map = serializer.serialize_map(Some(self.len()))?;
                for (key, value) in self {
                    let key_name = key.as_ref();
                    if !policy.is_disabled() {
                        if let Some(level) = policy.sensitivity_for(key_name) {
                            let masked = policy.masking().mask_opaque(level).to_owned();
                            map.serialize_entry(key, &masked)?;
                            continue;
                        }
                    }
                    map.serialize_entry(key, value)?;
                }
                map.end()
            }
        }

        impl<K, V> RedactMapSerialize for Option<$map>
        where
            K: AsRef<str> + serde::Serialize,
            V: serde::Serialize,
        {
            fn serialize_redacted_map<S>(
                &self,
                serializer: S,
                policy: &crate::RedactionPolicy,
            ) -> Result<S::Ok, S::Error>
            where
                S: serde::Serializer,
            {
                match self {
                    Some(value) => value.serialize_redacted_map(serializer, policy),
                    None => serializer.serialize_none(),
                }
            }
        }
    };
}

map_redact_serialize!(HashMap<K, V>);
map_redact_serialize!(BTreeMap<K, V>);

/// Internal structured serialization capability for JSON text fields.
#[doc(hidden)]
#[cfg(feature = "json")]
pub trait RedactJsonSerialize {
    fn serialize_redacted_json<S>(&self, serializer: S, policy: &crate::RedactionPolicy) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer;
}

/// Borrowed serializer adapter for one JSON text field.
#[doc(hidden)]
#[cfg(feature = "json")]
pub struct RedactedJsonSerializeRef<'value, 'policy, T: ?Sized> {
    value: &'value T,
    policy: &'policy crate::RedactionPolicy,
}

#[cfg(feature = "json")]
impl<'value, 'policy, T: ?Sized> RedactedJsonSerializeRef<'value, 'policy, T> {
    /// Creates a policy-carrying borrowed JSON adapter.
    #[must_use]
    pub fn new(value: &'value T, policy: &'policy crate::RedactionPolicy) -> Self {
        Self { value, policy }
    }
}

#[cfg(feature = "json")]
impl<T: ?Sized + RedactJsonSerialize> serde::Serialize for RedactedJsonSerializeRef<'_, '_, T> {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        self.value.serialize_redacted_json(serializer, self.policy)
    }
}

#[cfg(feature = "json")]
fn serialize_json_text<S>(serializer: S, text: &str, policy: &crate::RedactionPolicy) -> Result<S::Ok, S::Error>
where
    S: serde::Serializer,
{
    let masked = || policy.masking().mask_opaque(crate::Sensitivity::Secret);
    if !admit_input(text.len()) {
        let replacement = masked();
        return serializer.serialize_str(replacement.as_ref());
    }
    if policy.is_disabled() {
        return serializer.serialize_str(text);
    }
    if text.len() > policy.limits().max_input_bytes() {
        let replacement = masked();
        return serializer.serialize_str(replacement.as_ref());
    }
    let Ok(mut value) = serde_json::from_str::<serde_json::Value>(text) else {
        let replacement = masked();
        return serializer.serialize_str(replacement.as_ref());
    };
    let mut session = crate::Redactor::new(policy.clone()).inspection_runtime();
    if !session.admit_input(text.len()) || !session.admit_json_value(&value) {
        let replacement = masked();
        return serializer.serialize_str(replacement.as_ref());
    }
    let unkeyed = match policy.unkeyed_json_value_policy() {
        crate::UnkeyedJsonValuePolicy::PassThrough => {
            crate::formats::json::internal::JsonUnkeyedValuePolicy::PassThrough
        }
        crate::UnkeyedJsonValuePolicy::Redact => {
            let marker = policy.masking().mask_opaque(crate::Sensitivity::Secret);
            crate::formats::json::internal::JsonUnkeyedValuePolicy::Redact { marker }
        }
    };
    crate::formats::json::internal::JsonRedactionState::from_policy(policy, unkeyed).redact(&mut value);
    serde::Serialize::serialize(&value, serializer)
}

#[cfg(feature = "json")]
impl RedactJsonSerialize for String {
    fn serialize_redacted_json<S>(&self, serializer: S, policy: &crate::RedactionPolicy) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        serialize_json_text(serializer, self.as_str(), policy)
    }
}

#[cfg(feature = "json")]
impl RedactJsonSerialize for str {
    fn serialize_redacted_json<S>(&self, serializer: S, policy: &crate::RedactionPolicy) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        serialize_json_text(serializer, self, policy)
    }
}

#[cfg(feature = "json")]
impl RedactJsonSerialize for &str {
    fn serialize_redacted_json<S>(&self, serializer: S, policy: &crate::RedactionPolicy) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        serialize_json_text(serializer, self, policy)
    }
}

#[cfg(feature = "json")]
impl<'a> RedactJsonSerialize for Cow<'a, str> {
    fn serialize_redacted_json<S>(&self, serializer: S, policy: &crate::RedactionPolicy) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        serialize_json_text(serializer, self.as_ref(), policy)
    }
}

#[cfg(feature = "json")]
impl RedactJsonSerialize for Option<String> {
    fn serialize_redacted_json<S>(&self, serializer: S, policy: &crate::RedactionPolicy) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        match self {
            Some(value) => serialize_json_text(serializer, value, policy),
            None => serializer.serialize_none(),
        }
    }
}

#[cfg(feature = "json")]
impl RedactJsonSerialize for Option<&str> {
    fn serialize_redacted_json<S>(&self, serializer: S, policy: &crate::RedactionPolicy) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        match self {
            Some(value) => serialize_json_text(serializer, value, policy),
            None => serializer.serialize_none(),
        }
    }
}

#[cfg(feature = "json")]
impl<'a> RedactJsonSerialize for Option<Cow<'a, str>> {
    fn serialize_redacted_json<S>(&self, serializer: S, policy: &crate::RedactionPolicy) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        match self {
            Some(value) => serialize_json_text(serializer, value, policy),
            None => serializer.serialize_none(),
        }
    }
}

macro_rules! tuple_redact_serialize {
    ($count:expr; $($name:ident => $index:tt),+) => {
        impl<$($name: RedactSerialize),+> RedactSerialize for ($($name,)+) {
            fn serialize_redacted<S>(&self, serializer: S, policy: &crate::RedactionPolicy) -> Result<S::Ok, S::Error>
            where
                S: serde::Serializer,
            {
                if !admit_collection_items($count) {
                    return serializer.serialize_str(
                        policy
                            .masking()
                            .mask_opaque(crate::Sensitivity::Secret)
                            .as_ref(),
                    );
                }
                let mut tuple = serializer.serialize_tuple($count)?;
                $(tuple.serialize_element(&RedactedSerializeRef::new(&self.$index, policy))?;)+
                tuple.end()
            }
        }
    };
}

tuple_redact_serialize!(1; A => 0);
tuple_redact_serialize!(2; A => 0, B => 1);
tuple_redact_serialize!(3; A => 0, B => 1, C => 2);
tuple_redact_serialize!(4; A => 0, B => 1, C => 2, D => 3);
tuple_redact_serialize!(5; A => 0, B => 1, C => 2, D => 3, E => 4);
tuple_redact_serialize!(6; A => 0, B => 1, C => 2, D => 3, E => 4, F => 5);
tuple_redact_serialize!(7; A => 0, B => 1, C => 2, D => 3, E => 4, F => 5, G => 6);
tuple_redact_serialize!(8; A => 0, B => 1, C => 2, D => 3, E => 4, F => 5, G => 6, H => 7);
tuple_redact_serialize!(9; A => 0, B => 1, C => 2, D => 3, E => 4, F => 5, G => 6, H => 7, I => 8);
tuple_redact_serialize!(10; A => 0, B => 1, C => 2, D => 3, E => 4, F => 5, G => 6, H => 7, I => 8, J => 9);
tuple_redact_serialize!(11; A => 0, B => 1, C => 2, D => 3, E => 4, F => 5, G => 6, H => 7, I => 8, J => 9, K => 10);
tuple_redact_serialize!(12; A => 0, B => 1, C => 2, D => 3, E => 4, F => 5, G => 6, H => 7, I => 8, J => 9, K => 10, L => 11);
