/// Internal structured serialization capability generated by the derive crate.
#[doc(hidden)]
pub trait RedactSerialize {
    fn serialize_redacted<S>(&self, serializer: S, policy: &crate::RedactionPolicy) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer;
}
