// =============================================================================
//    Copyright (c) 2025 - 2026 Haixing Hu.
//
//    SPDX-License-Identifier: Apache-2.0
//
//    Licensed under the Apache License, Version 2.0.
// =============================================================================
//! Bounded streaming log-control escaping.

use std::{
    fmt::{
        self,
        Write,
    },
    str,
};

use crate::{
    LogOutputLimit,
    text::{
        log_escape::is_log_unsafe_character,
        log_output_limit::TRUNCATION_MARKER,
    },
};

/// Escapes log-unsafe characters into a byte-bounded owned string.
pub(crate) struct BoundedLogEscapeWriter {
    /// Output retained within the configured byte budget.
    output: String,
    /// Maximum output bytes including the truncation marker.
    max_bytes: usize,
    /// Last complete piece boundary that leaves room for the marker.
    marker_boundary: usize,
    /// Whether output has already been finalized with the marker.
    truncated: bool,
}

impl BoundedLogEscapeWriter {
    /// Creates a bounded escaping destination.
    ///
    /// # Parameters
    ///
    /// * `limit` - Validated maximum output byte count.
    ///
    /// # Returns
    ///
    /// An empty bounded writer.
    #[inline]
    pub(crate) fn new(limit: LogOutputLimit) -> Self {
        Self {
            output: String::new(),
            max_bytes: limit.max_bytes(),
            marker_boundary: 0,
            truncated: false,
        }
    }

    /// Returns the completed bounded log-safe output.
    ///
    /// # Returns
    ///
    /// The escaped output, with a marker when truncation occurred.
    #[inline(always)]
    pub(crate) fn finish(self) -> String {
        self.output
    }

    /// Appends one complete UTF-8 character or escape sequence.
    ///
    /// # Parameters
    ///
    /// * `piece` - Atomic log-safe text corresponding to one input character.
    fn write_piece(&mut self, piece: &str) {
        if self.truncated {
            return;
        }
        if piece.len() <= self.max_bytes - self.output.len() {
            self.output.push_str(piece);
            let payload_limit = self.max_bytes - TRUNCATION_MARKER.len();
            if self.output.len() <= payload_limit {
                self.marker_boundary = self.output.len();
            }
            return;
        }
        self.output.truncate(self.marker_boundary);
        self.output.push_str(TRUNCATION_MARKER);
        self.truncated = true;
    }
}

impl Write for BoundedLogEscapeWriter {
    /// Writes escaped text without exceeding the configured byte budget.
    ///
    /// # Parameters
    ///
    /// * `value` - Redacted text to escape and append.
    ///
    /// # Returns
    ///
    /// `Ok(())` after the input has been processed.
    ///
    /// # Errors
    ///
    /// This in-memory writer does not return formatting errors.
    fn write_str(&mut self, value: &str) -> fmt::Result {
        for character in value.chars() {
            let mut buffer = [0_u8; 12];
            let piece = encode_log_safe_character(character, &mut buffer)?;
            self.write_piece(piece);
        }
        Ok(())
    }
}

/// Encodes one input character as one atomic log-safe piece.
///
/// # Parameters
///
/// * `character` - Input character to encode.
/// * `buffer` - Scratch storage large enough for any debug escape.
///
/// # Returns
///
/// A UTF-8 slice containing either the original character or its complete
/// debug escape.
///
/// # Errors
///
/// Returns [`fmt::Error`] if the internally generated bytes are not UTF-8.
fn encode_log_safe_character(
    character: char,
    buffer: &mut [u8; 12],
) -> Result<&str, fmt::Error> {
    let length = if is_log_unsafe_character(character) {
        let mut length = 0;
        for escaped in character.escape_debug() {
            let encoded = escaped.encode_utf8(&mut buffer[length..]);
            length += encoded.len();
        }
        length
    } else {
        character.encode_utf8(buffer).len()
    };
    str::from_utf8(&buffer[..length]).map_err(|_| fmt::Error)
}
